version: '2.3'
services:
    elasticsearch:
        build:
            context: ./elasticsearch
            dockerfile: dockerfile
        container_name: elasticsearch-sudachi
        volumes:
            - ./node_data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        tty: true

    ubuntu:
        build:
            context: ./ubuntu
            dockerfile: dockerfile
        container_name: ubuntu
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - ./program_ubuntu:/home/docker/programs
        ports:
            - 8888:8888
        tty: true
